version: '3'
services:
  client:
    image: nandinikodipunzula/multi-container-project-client
    hostname: client
    mem_limit: 512m
  server:
    image: nandinikodipunzula/multi-container-project-server
    hostname: api
    mem_limit: 512m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: nandinikodipunzula/multi-container-project-worker
    hostname: worker
    mem_limit: 512m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: nandinikodipunzula/multi-container-project-nginx
    hostname: nginx
    mem_limit: 512m
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server


   


