name: Deploy Multi-Container App
on:
  push:
    branches:
      - main 
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build  -t nandinikodipunzula/multi-container-project -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true nandinikodipunzula/multi-container-project npm test -- --coverage

      - run: docker build -t nandinikodipunzula/multi-container-project-client ./client
      - run: docker build -t nandinikodipunzula/multi-container-project-nginx ./nginx
      - run: docker build -t nandinikodipunzula/multi-container-project-server ./server
      - run: docker build -t nandinikodipunzula/multi-container-project-worker ./worker

      - run: docker push nandinikodipunzula/multi-container-project-client
      - run: docker push nandinikodipunzula/multi-container-project-nginx
      - run: docker push nandinikodipunzula/multi-container-project-server
      - run: docker push nandinikodipunzula/multi-container-project-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to Elastic Bean
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container-docker
          environment_name: Multi-container-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-2-975049916169
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip