name: Deploy Multi-Container App
on:
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build  -t nandinikodipunzula/multi-container-project -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true nandinikodipunzula/multi-container-project npm test -- --coverage

      - run: docker build -t nandinikodipunzula/multi-container-project-client ./client
      - run: docker build -t nandinikodipunzula/multi-container-project-nginx ./nginx
      - run: docker build -t nandinikodipunzula/multi-container-project-server ./server
      - run: docker build -t nandinikodipunzula/multi-container-project-worker ./worker

      - run: docker push nandinikodipunzula/multi-container-project-client
      - run: docker push nandinikodipunzula/multi-container-project-nginx
      - run: docker push nandinikodipunzula/multi-container-project-server
      - run: docker push nandinikodipunzula/multi-container-project-worker